"""store profile

Revision ID: 74915bf3d538
Revises: 3621e815bd33
Create Date: 2024-03-27 16:46:28.174018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74915bf3d538'
down_revision: Union[str, None] = '3621e815bd33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(), nullable=False))
        batch_op.drop_column('store_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('store profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
