"""stores

Revision ID: 92474a5ecf89
Revises: 8a351183da70
Create Date: 2024-03-29 13:02:09.883042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92474a5ecf89'
down_revision: Union[str, None] = '8a351183da70'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('ordered_item', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint('company', type_='foreignkey')
        batch_op.drop_column('company_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('ordered_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('deliveries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('company', 'companies', ['company_id'], ['id'])

    # ### end Alembic commands ###
